name: fton
description: "73% of app users want to better manage their reproductive health using smart technology. With FTON each women can earn money on tracking her cycle"
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  telegram_web_app: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
