name: fton
description: "73% of app users want to better manage their reproductive health using smart technology. With FTON each women can earn money on tracking her cycle"
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  telegram_web_app: ^0.1.0
  provider: ^6.1.2
  darttonconnect: ^1.0.3
  pretty_qr_code: ^3.3.0
  flutter_secure_storage: ^9.2.2
  ton:
    path: packages/ton
  go_router:
    git:
      url: https://github.com/tolo/flutter_packages.git
      ref: statefulshellroute-preload-v2
      path: packages/go_router

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  js: ^0.7.1
  http: ^1.2.1
  intl: 0.19.0

flutter:
  uses-material-design: true
